name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Make tester.exe executable
      run: |
        chmod +x 029/tools_windows/tester.exe

    - name: Run tests
      run: |
        for file in 029/tools_windows/in/*.txt; do
          cat "$file" | ./029/tools_windows/tester.exe python main.py > out.txt
          # Add further commands or assertions as needed
        done
